const router = require('express').Router()

const auth = require('~/routes/auth')
const user = require('~/routes/user')
const email = require('~/routes/email')
const review = require('~/routes/review')
const subject = require('~/routes/subject')
const location = require('~/routes/location')
const adminInvitation = require('~/routes/adminInvitation')
const offer = require('~/routes/offer')
const category = require('~/routes/category')
const cooperation = require('~/routes/cooperation')
const note = require('~/routes/note')
const lesson = require('~/routes/lesson')
const chat = require('~/routes/chat')
const message = require('~/routes/message')
const notification = require('~/routes/notification')
const course = require('~/routes/course')
const quiz = require('~/routes/quiz')
const attachment = require('~/routes/attachment')
const finishedQuiz = require('~/routes/finishedQuiz')
const question = require('~/routes/question')
const resourcesCategory = require('~/routes/resourcesCategory')
const coursesCooperations = require('~/routes/coursesCooperations')

router.use('/auth', auth)
router.use('/users', user)
router.use('/send-email', email)
router.use('/reviews', review)
router.use('/subjects', subject)
router.use('/location', location)
router.use('/admin-invitations', adminInvitation)
router.use('/offers', offer)
router.use('/categories', category)
router.use('/cooperations', cooperation)
router.use('/notes', note)
router.use('/lessons', lesson)
router.use('/chats', chat)
router.use('/messages', message)
router.use('/notifications', notification)
router.use('/courses', course)
router.use('/quizzes', quiz)
router.use('/attachments', attachment)
router.use('/finished-quizzes', finishedQuiz)
router.use('/questions', question)
router.use('/resources-categories', resourcesCategory)
router.use('/courses-cooperations', coursesCooperations)

module.exports = router
