const router = require('express').Router()

const auth = require('~/app/routes/auth')
const user = require('~/app/routes/user')
const email = require('~/app/routes/email')
const review = require('~/app/routes/review')
const subject = require('~/app/routes/subject')
const location = require('~/app/routes/location')
const adminInvitation = require('~/app/routes/adminInvitation')
const offer = require('~/app/routes/offer')
const category = require('~/app/routes/category')
const cooperation = require('~/app/routes/cooperation')
const note = require('~/app/routes/note')
const lesson = require('~/app/routes/lesson')
const chat = require('~/app/routes/chat')
const message = require('~/app/routes/message')
const notification = require('~/app/routes/notification')
const course = require('~/app/routes/course')
const quiz = require('~/app/routes/quiz')
const attachment = require('~/app/routes/attachment')
const finishedQuiz = require('~/app/routes/finishedQuiz')
const question = require('~/app/routes/question')
const resourcesCategory = require('~/app/routes/resourcesCategory')

router.use('/auth', auth)
router.use('/users', user)
router.use('/send-email', email)
router.use('/reviews', review)
router.use('/subjects', subject)
router.use('/location', location)
router.use('/admin-invitations', adminInvitation)
router.use('/offers', offer)
router.use('/categories', category)
router.use('/cooperations', cooperation)
router.use('/notes', note)
router.use('/lessons', lesson)
router.use('/chats', chat)
router.use('/messages', message)
router.use('/notifications', notification)
router.use('/courses', course)
router.use('/quizzes', quiz)
router.use('/attachments', attachment)
router.use('/finished-quizzes', finishedQuiz)
router.use('/questions', question)
router.use('/resources-categories', resourcesCategory)

module.exports = router
