const emailSubject = {
  EMAIL_CONFIRMATION: 'EMAIL_CONFIRMATION',
  RESET_PASSWORD: 'RESET_PASSWORD',
  SUCCESSFUL_PASSWORD_RESET: 'SUCCESSFUL_PASSWORD_RESET',
  LONG_TIME_WITHOUT_LOGIN: 'LONG_TIME_WITHOUT_LOGIN'
}

module.exports = emailSubject
