const authErr = {
  INCORRECT_CREDENTIALS: 'INCORRECT_CREDENTIALS',
  ROLE_NOT_SUPPORTED: 'ROLE_NOT_SUPPORTED',
  PASS_LENGTH: 'PASS_LENGTH',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
}

const statusCodes = {
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  INTERNAL: 500,
}

module.exports = {
  authErr,
  statusCodes,
}
