name: CI feature/** branch

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ ! "$BRANCH_NAME" =~ ^feature/[0-9]+/.+ ]]; then
            echo "❌ Branch name is incorrect! Expected format: feature/issue_number/problem_name"
            exit 1
          fi
          echo "✅ Branch name is valid"

  test:
    needs: check-branch-name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        mongodb-version: ['8.0']
      max-parallel: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: ${{ secrets.MONGODB_DB }}
          mongodb-username: ${{ secrets.MONGODB_USER }}
          mongodb-password: ${{ secrets.MONGODB_PASS }}
          mongodb-port: 27017

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
