name: CI PR Feature to Main

on:
  pull_request:
    branches: ['develop']

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '22.x' ]          # NodeJS version   | Use this to test new NodeJS versions
        mongodb-version: [ '8.0' ]        # MongoDB version  | Use this to test new MongoDB versions   
      max-parallel: 1                     # The maximum number of jobs run in parallel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # - name: Install MongoDB ${{ matrix.mongodb-version }}
      #   uses: supercharge/mongodb-github-action@1.12.0
      #   with:
      #     mongodb-version: ${{ matrix.mongodb-version }}
      #     mongodb-db: ${{ secrets.MONGODB_DB }}
      #     mongodb-username: ${{ secrets.MONGODB_USER }}
      #     mongodb-password: ${{ secrets.MONGODB_PASS }}
      #     mongodb-port: 27017
      
      # - name: Install MongoDB shell
      #   run: |
      #     sudo apt-get install -y gnupg curl
      #     curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
      #     sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
      #     --dearmor
      #     echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/8.0 multiverse" | \
      #     sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
      #     sudo apt-get update && sudo apt-get install -y mongodb-mongosh
       
      # - name: Check MongoDB
      #   run: |
      #     for i in {1..30}; do
      #       mongosh --eval "db.runCommand({ ping: 1 })" localhost:27017 && echo "MongoDB is up" && exit 0
      #       echo "Waiting for MongoDB..."
      #       sleep 2
      #     done
      #     echo "MongoDB did not start in time!" && exit 1
      
      - name: Install dependencies
        run: npm install
       # run: npm ci        # TO-DO: Install dependencies from package-lock.json
      
      # - name: Run ESLint    # TO-DO: add linter check
      #   run: npm run lint
        
      - name: Run tests
        run: |
          npm test -- src/test/unit/cron-jobs/checkForLastLogin.spec.js --verbose --coverage=false 2>&1 | \
          tee "full-tests-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" | \
          tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > \
          "tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.txt") || true
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          MONGODB_URL: mongodb://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASS }}@localhost:27017/${{ secrets.MONGODB_DB }}?authSource=admin
          MONGODB_URL_READONLY_TEST: ${{ secrets.MONGODB_URL_READONLY_TEST }}
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          JWT_RESET_SECRET: ${{ secrets.JWT_RESET_SECRET }}
          JWT_CONFIRM_SECRET: ${{ secrets.JWT_CONFIRM_SECRET }}
          JWT_ACCESS_EXPIRES_IN: ${{ secrets.JWT_ACCESS_EXPIRES_IN }}
          JWT_REFRESH_EXPIRES_IN: ${{ secrets.JWT_REFRESH_EXPIRES_IN }}
          JWT_REFRESH_LONG_TERM_EXPIRES_IN: ${{ secrets.JWT_REFRESH_LONG_TERM_EXPIRES_IN }}
          JWT_RESET_EXPIRES_IN: ${{ secrets.JWT_RESET_EXPIRES_IN }}
          JWT_CONFIRM_EXPIRES_IN: ${{ secrets.JWT_CONFIRM_EXPIRES_IN }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_FIRSTNAME: ${{ secrets.MAIL_FIRSTNAME }}
          MAIL_LASTNAME: ${{ secrets.MAIL_LASTNAME }}
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          GMAIL_REDIRECT_URI: ${{ secrets.GMAIL_REDIRECT_URI }}
          COOKIE_DOMAIN: ${{ secrets.COOKIE_DOMAIN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Extract Errors
        run: |
          awk '/Summary of all failing tests/,/Test Suites/{if ($0 !~ /Test Suites/) print}' \
          "full-tests-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" > \
          "test-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" || true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}
          path: |
            tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.txt
            test-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log
  
  docker-build-test:
    name: Build & Test Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Build Docker Image
        run: docker build -t be-app:test -f ./Dockerfile .
  
      - name: Run Docker Container
        run: |
          docker run -d --name be-app -p 8080:8080 be-app:test
          sleep 10

      - name: Check if container is running
        run: |
          docker ps -a
        
      - name: Test API Unauthorized Response
        run: |
          RESPONSE=$(curl --silent --request GET \
            --url 'http://localhost:8080/users/' \
            --write-out "\n%{http_code}")
          BODY=$(echo "$RESPONSE" | head -n 1)
          STATUS_CODE=$(echo "$RESPONSE" | tail -n 1)
  
          EXPECTED_BODY='{"status":401,"code":"UNAUTHORIZED","message":"The requested URL requires user authorization."}'
          EXPECTED_STATUS=401
          
          if [[ "$BODY" == "$EXPECTED_BODY" && "$STATUS_CODE" == "$EXPECTED_STATUS" ]]; then
            echo "✅ API returned expected unauthorized response!"
          else
            echo "❌ API response mismatch!"
            echo "Expected: $EXPECTED_BODY ($EXPECTED_STATUS)"
            echo "Got: $BODY ($STATUS_CODE)"
            docker logs be-app
            exit 1
          fi
      
      - name: Cleanup Docker Container & Image
        run: |
          docker stop be-app
          docker rm be-app
          docker rmi be-app:test
  
  generate-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: ['run-tests', 'docker-build-test']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download All Test Results
        uses: actions/download-artifact@v4
        with:
          path: test-reports

      - name: Generate Test Report
        run: |
          CI_MARKER="### ✅ CI Report - $(TZ="Europe/Kyiv" date +"%H:%M %d/%m/%Y")"
          echo "$CI_MARKER" > test-report.txt
          echo "" >> test-report.txt
          for folder in test-reports/tests-results-*; do
            TEST_VERSION=$(basename "$folder")
            NODE_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f3)
            MONGO_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f4)
            TEST_FILE="$folder/tests-results-$NODE_VERSION-$MONGO_VERSION.txt"
            ERRORS_FILE="$folder/test-errors-$NODE_VERSION-$MONGO_VERSION.log"
            echo "**🔹 Node.js Version:** $NODE_VERSION" >> test-report.txt
            echo "**🔹 MongoDB Version:** $MONGO_VERSION" >> test-report.txt
            echo "" >> test-report.txt
            echo "### 🧪 Test Results" >> test-report.txt
            echo '```' >> test-report.txt
            cat "$TEST_FILE" >> test-report.txt
            echo '```' >> test-report.txt
            echo "" >> test-report.txt
            if [[ -s "$ERRORS_FILE" ]]; then
              echo "### ❌ Test Errors" >> test-report.txt
              echo '```' >> test-report.txt
              cat "$ERRORS_FILE" >> test-report.txt
              echo '```' >> test-report.txt
            fi
            echo "" >> test-report.txt
          done

      - name: Publish Report in GitHub Actions Summary
        run: cat test-report.txt >> $GITHUB_STEP_SUMMARY
        
      - name: Update CI Report in PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [[ -z "$PR_NUMBER" ]]; then
            echo "No PR associated, skipping update."
            exit 0
          fi
          
          COMMENT_ID=$(gh api repos/:owner/:repo/issues/$PR_NUMBER/comments --jq '.[] | select(.user.login=="github-actions[bot]") | select(.body | contains("### ✅ CI Report")) | .id')

          if [[ -n "$COMMENT_ID" ]]; then
            echo "Updating existing CI report comment: $COMMENT_ID"
            gh api repos/:owner/:repo/issues/comments/$COMMENT_ID -X PATCH -f body="$(cat test-report.txt)"
          else
            echo "No previous CI report found, creating a new one..."
            gh pr comment $PR_NUMBER --body-file test-report.txt
          fi
